script: 
- make -j2
- cpack -C Debug
compiler: 
- gcc
env: 
  matrix: 
    secure: nc4k28vUUeFeqfXdqquyLPErFqtx0tSfotGFArvrSJ0gsiXucoBNNqmbHkMDjyHvBsDXhSJ3TSxIL0xeyKspu3hMR7XIFItxrnCtI5DbmiyUdL3JDOPZlUx9pgMW9r8RqbTHIHl4E6DFskhd2lMay6nKsN5Cls6uhhNvD3h+GHA=
before_install: 
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:boost-latest/ppa -y
- sudo apt-get update
- sudo apt-get install boost1.55
- sudo apt-get install gcc-4.9
- sudo apt-get install g++-4.9
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
- sudo update-alternatives --config gcc
- sudo update-alternatives --config g++
- sudo apt-get install libvorbis-dev
- sudo apt-get install libalut-dev
- sudo apt-get install libfreetype6-dev
- sudo apt-get install libfreeimage-dev
- sudo apt-get install zlib1g-dev
- sudo apt-get install libzzip-dev
- sudo apt-get install libois-dev
- sudo apt-get install libglu-dev
- wget https://github.com/paulsapps/Ogre1.9/releases/download/1.9.0/ogre-build_1.9.0-1_amd64.deb
- sudo dpkg -i ogre-build_1.9.0-1_amd64.deb
notifications: 
  on_success: change
  on_failure: always
  irc: irc.esper.net#qhimm.com
before_script: 
- mkdir build_qgears
- cd build_qgears
- cmake ..
after_success:
- hash=`git rev-parse HEAD`
- mkdir ~/.ssh
- cat $KEY > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- chmod 755 ~/.ssh
- ssh -o StrictHostKeyChecking=no paul@itscovarr.com mkdir -p /var/www/storage/qgears/$hash/linux/
- scp -o StrictHostKeyChecking=no ~/build/*.deb paul@itscovarr.com:/var/www/storage/qgears/$hash/linux/
language: cpp
